name: BERLO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40807
title: BERLO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#be0000'
    - '#efd600'
    - '#1b1c33'
    - '#92630b'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
