name: BERLO
favicon: null
layout_spectrum: 0.9443994755856693
typography_spectrum: 0.17057256517000496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9563520245719701
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
