name: Berlo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30586
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4e4e4e'
    - '#8d8d8d'
    - '#cacaca'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
