title: BerloAtelier
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#fdfdfb'
    - '#0d0c11'
    - '#44434a'
    - '#7a797b'
    - '#c0bec2'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-634542-13
  facebook: null
name: Berlo
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.30388
layout_spectrum: 0.03829787
