name: Berlo
favicon: null
layout_spectrum: 0.23965
typography_spectrum: 0.9473
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7b6b2'
    - '#938e7b'
    - '#646150'
    - '#d4ccc1'
    - '#282723'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
