name: BERLO
favicon: null
layout_spectrum: 0.50942
typography_spectrum: 0.79263
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1cbda'
    - '#5b97dd'
    - '#181c1b'
    - '#5c5855'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
