name: Berlo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30406
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dcdd'
    - '#aaafb2'
    - '#15141c'
    - '#55443a'
    - '#fcb683'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
