name: Berlo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30388
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfb'
    - '#0d0c11'
    - '#44434a'
    - '#7a797b'
    - '#c0bec2'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
