name: Berlo
favicon: null
layout_spectrum: 0.50632
typography_spectrum: 0.30586
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d1c5'
    - '#0d0a05'
    - '#868e90'
    - '#8d211f'
    - '#63645f'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
