name: BERLO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79263
title: BERLO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f3735'
    - '#bebcbb'
    - '#dddcda'
    - '#a29e9c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
