name: Berlo
favicon: null
layout_spectrum: 0.18145
typography_spectrum: 0.33108
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c2c2c0'
    - '#917762'
    - '#6b4c29'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
