name: BERLO
favicon: null
layout_spectrum: 0.76422
typography_spectrum: 0.79263
title: BerloAtelier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#747c84'
    - '#050601'
    - '#424243'
    - '#bcb99d'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
