name: Berlo
favicon: null
layout_spectrum: 0.35057
typography_spectrum: 0.30388
title: Berlo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181818'
    - '#606060'
    - '#8d8d8d'
    - '#89bfde'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
