name: BERLO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79263
title: concept and development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-634542-13
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f3735'
    - '#bebcbb'
    - '#dddcda'
    - '#a29e9c'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
